### ISSUE TITLE
[RFC] Support for TileJSON as a backend source

### ISSUE THREAD

**Issue by jerluc** [StationA/tilenol#36]
tilenol could greatly benefit from the vast majority of tile servers and their data sources that are currently unsupported, and likely to not be supported for a while. In order to provide a simple means of sort of "bridging" this gap, we could potentially implement a new backend data source which allows tilenol to operate as a sort of "frontend" to both raw backend data sources and other tile servers. For example:

```yaml
layers:
  - name: trees
    source:
      tilejson:
        url: https://my.tile.server/tilejson
        layer: trees
  - name: buildings
    source:
      postgis:
        ...
```

In this example, tilenol would act as a common "frontend" to both the `trees` layer (coming from a backend tile server), and the `buildings` layer (coming directly from PostGIS).

Another interesting thought is that if we were to implement #6 , we could also benefit from the fact that a tilenol server could act as that unified "frontend" for even other tilenol servers, and form a kind of "federated" service.
